title: Ecliptic Innovations
description: 'A NASA/space themed, neurodivergent-friendly Jekyll blog for kids.'
remote_theme: pages-themes/cayman
markdown: kramdown
highlighter: rouge
paginate: 5
baseurl: "/Ecliptic-Web"
plugins:
  - jekyll-gist
permalink: /:year/:month/:title.html
