title: Ecliptic Web
email: your-email@domain.com
description: A modern Jekyll blog powered by Avalon theme
baseurl: /Ecliptic-Web
url: https://yourusername.github.io
twitter_username: yourusername
github_username: yourusername

sass:
  style: compressed

paginate: 12
paginate_path: "/:num/"

author_img_s: /img/author_s.png
author_img: /img/author.png

navigation:
  - text: Home
    url: /
  - text: Categories
    url: /categories.html
  - text: Tags
    url: /tags.html

read_more: Read More

# Build settings
markdown: kramdown

sticky: sticky # Tag used for sticky post
sticky_count: 3 # Number of sticky post shown

plugins:
  - jekyll-paginate
  - jekyll-feed
  
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
